import { CourseListType } from "../Api/CourseSearch/types/courseListTypes";

export const courseList: CourseListType = [
  {
    id: 1,
    courseCode: "BS3101",
    courseName: "생화학 II",
    courseCredit: 3,
    prerequisite: "NONE",
    courseTags: ["전공"],
  },
  {
    id: 2,
    courseCode: "BS3111",
    courseName: "생화학·분자생물학 실험",
    courseCredit: 3,
    prerequisite: "none",
    courseTags: ["전공"],
  },
  {
    id: 3,
    courseCode: "BS3201",
    courseName: "미생물학",
    courseCredit: 3,
    prerequisite: "-",
    courseTags: ["전공"],
  },
  {
    id: 4,
    courseCode: "BS3204",
    courseName: "생물물리 화학 입문",
    courseCredit: 3,
    prerequisite: "",
    courseTags: ["전공"],
  },
  {
    id: 5,
    courseCode: "BS4101",
    courseName: "세포생물학  II",
    courseCredit: 3,
    prerequisite: "",
    courseTags: ["전공"],
  },
  {
    id: 6,
    courseCode: "BS4201",
    courseName: "발생생물학",
    courseCredit: 3,
    prerequisite: "-",
    courseTags: ["전공"],
  },
  {
    id: 7,
    courseCode: "BS4204",
    courseName: "신경생물학",
    courseCredit: 3,
    prerequisite: "-",
    courseTags: ["전공"],
  },
  {
    id: 8,
    courseCode: "BS4208",
    courseName: "식물학",
    courseCredit: 3,
    prerequisite: "GS1301 or GS1302",
    courseTags: ["전공"],
  },
  {
    id: 9,
    courseCode: "BS9101",
    courseName: "학사논문연구",
    courseCredit: 3,
    prerequisite: "",
    courseTags: ["전공"],
  },
  {
    id: 10,
    courseCode: "BS9201",
    courseName: "개별연구",
    courseCredit: 1,
    prerequisite: "",
    courseTags: ["전공"],
  },
  {
    id: 11,
    courseCode: "CM3102",
    courseName: "화학합성실험",
    courseCredit: 3,
    prerequisite: "-",
    courseTags: [],
  },
  {
    id: 12,
    courseCode: "CM3104",
    courseName: "물리화학 II",
    courseCredit: 3,
    prerequisite: "GS2202 Physical Chemistry I",
    courseTags: [],
  },
  {
    id: 13,
    courseCode: "CM3105",
    courseName: "유기화학 II",
    courseCredit: 3,
    prerequisite: "Organic Chemistry I",
    courseTags: [],
  },
  {
    id: 14,
    courseCode: "CM4205",
    courseName: "생유기화학",
    courseCredit: 3,
    prerequisite: "Organic Chemistry I",
    courseTags: [],
  },
  {
    id: 15,
    courseCode: "CM4206",
    courseName: "에너지화학",
    courseCredit: 3,
    prerequisite: "Physical Chemistry, Thermodynamics",
    courseTags: [],
  },
  {
    id: 16,
    courseCode: "CM4209",
    courseName: "표면물리화학",
    courseCredit: 3,
    prerequisite: "Recommendation: Physical Chemistry I, Physical Chemistry II",
    courseTags: [],
  },
  {
    id: 17,
    courseCode: "CM4210",
    courseName: "고급물리화학",
    courseCredit: 3,
    prerequisite: "Physical Chemistry I, Physical Chemistry II",
    courseTags: [],
  },
  {
    id: 18,
    courseCode: "CM4212",
    courseName: "양자화학",
    courseCredit: 3,
    prerequisite: "CM3104 (Physical Chemistry II)",
    courseTags: [],
  },
  {
    id: 19,
    courseCode: "CM4213",
    courseName: "기기분석",
    courseCredit: 3,
    prerequisite: "",
    courseTags: [],
  },
  {
    id: 20,
    courseCode: "CM4216",
    courseName: "유기합성화학",
    courseCredit: 3,
    prerequisite: "Organic Chemistry I, Organic Chemistry II",
    courseTags: [],
  },
];
